# Generated by Django 3.2.2 on 2023-03-20 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='注册时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('is_del', models.BooleanField(verbose_name='是否删除')),
                ('name', models.CharField(max_length=32, verbose_name='部门名')),
                ('status', models.BooleanField(default=True, verbose_name='部门状态')),
                ('dept_count', models.IntegerField(null=True, verbose_name='子部门数量')),
                ('p_dept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='permission.dept', verbose_name='是否有父部门')),
            ],
            options={
                'verbose_name': '部门表',
                'verbose_name_plural': '部门表',
                'db_table': 'dept',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='注册时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('is_del', models.BooleanField(verbose_name='是否删除')),
                ('name', models.CharField(max_length=32, verbose_name='岗位名')),
                ('status', models.BooleanField(default=True, verbose_name='岗位状态')),
            ],
            options={
                'verbose_name': '岗位表',
                'verbose_name_plural': '岗位表',
                'db_table': 'job',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='注册时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('is_del', models.BooleanField(verbose_name='是否删除')),
                ('name', models.CharField(max_length=32, verbose_name='菜单名')),
                ('type', models.IntegerField(choices=[(0, '目录'), (1, '菜单'), (2, '按钮')], default=1, verbose_name='类型')),
                ('path', models.CharField(max_length=32, verbose_name='路由地址')),
                ('component', models.CharField(max_length=32, unique=True, verbose_name='前端组件名')),
                ('hidden', models.BooleanField(default=False, verbose_name='是否隐藏')),
                ('p_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='permission.menu')),
            ],
            options={
                'verbose_name': '菜单权限表',
                'verbose_name_plural': '菜单权限表',
                'db_table': 'rbac_rule_menu',
            },
        ),
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='注册时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('is_del', models.BooleanField(verbose_name='是否删除')),
                ('name', models.CharField(max_length=32, verbose_name='角色名')),
                ('msg', models.CharField(max_length=64, null=True, verbose_name='角色介绍')),
                ('status', models.BooleanField(default=True, verbose_name='角色状态')),
                ('depts', models.ManyToManyField(db_table='rule_dept', to='permission.Dept', verbose_name='角色和部门关联表')),
                ('menus', models.ManyToManyField(db_table='rule_menu', to='permission.Menu', verbose_name='菜单和角色关联表')),
            ],
            options={
                'verbose_name': '角色表',
                'verbose_name_plural': '角色表',
                'db_table': 'rules',
            },
        ),
    ]
