# Generated by Django 3.2.2 on 2023-03-20 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='menu',
            table='menu',
        ),
    ]
