# Generated by Django 3.2.2 on 2023-03-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0002_alter_menu_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='注册时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('is_del', models.BooleanField(verbose_name='是否删除')),
                ('name', models.CharField(max_length=32, verbose_name='角色名')),
                ('msg', models.CharField(max_length=64, null=True, verbose_name='角色介绍')),
                ('status', models.BooleanField(default=True, verbose_name='角色状态')),
            ],
            options={
                'verbose_name': '角色表',
                'verbose_name_plural': '角色表',
                'db_table': 'roles',
            },
        ),
        migrations.RemoveField(
            model_name='rules',
            name='depts',
        ),
        migrations.RemoveField(
            model_name='rules',
            name='menus',
        ),
    ]
