# Generated by Django 3.2.2 on 2023-03-20 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0004_auto_20230320_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='p_id',
            new_name='p_menu',
        ),
    ]
