# Generated by Django 3.2.2 on 2023-03-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0005_rename_p_id_menu_p_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dept',
            name='is_del',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='job',
            name='is_del',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='is_del',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='roles',
            name='is_del',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
    ]
