# Generated by Django 3.2.2 on 2023-03-21 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0006_auto_20230321_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='dept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='permission.dept'),
        ),
    ]
