# Generated by Django 3.2.2 on 2023-03-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0009_menu_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='permission',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
