# Generated by Django 3.2.2 on 2023-03-28 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0010_menu_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dept',
            name='dept_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='子部门数量'),
        ),
        migrations.AlterField(
            model_name='dept',
            name='p_dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='permission.dept', verbose_name='是否有父部门'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='component',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='前端组件名'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='path',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='路由地址'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='permission',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='title',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='roles',
            name='msg',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='角色介绍'),
        ),
    ]
