# Generated by Django 3.2.2 on 2023-03-28 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0011_auto_20230328_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
