# Generated by Django 3.2.2 on 2023-03-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0003_auto_20230320_1926'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='rules',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='roles',
            field=models.ManyToManyField(db_table='user_rules', to='permission.Roles', verbose_name='用户和角色关联表'),
        ),
    ]
