# Generated by Django 3.2.2 on 2023-03-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_userinfo_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='is_del',
            field=models.BooleanField(default=False, verbose_name='是否被删除'),
        ),
    ]
