# Generated by Django 3.2.2 on 2023-03-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userinfo_is_del'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='mobile',
            field=models.CharField(max_length=11, null=True, unique=True, verbose_name='手机号'),
        ),
    ]
