# Generated by Django 3.2.2 on 2023-03-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0008_auto_20230323_0944'),
        ('user', '0005_alter_userinfo_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='job',
            field=models.ManyToManyField(db_table='user_job', null=True, to='permission.Job', verbose_name='用户和岗位关联表'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='roles',
            field=models.ManyToManyField(db_table='user_rules', null=True, to='permission.Roles', verbose_name='用户和角色关联表'),
        ),
    ]
