# Generated by Django 3.2.2 on 2023-03-23 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20230323_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='is_lock',
            new_name='lock',
        ),
    ]
