# Generated by Django 3.2.2 on 2023-03-23 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_rename_is_lock_userinfo_lock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='lock',
            new_name='status',
        ),
    ]
