# Generated by Django 3.2.2 on 2023-03-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_rename_lock_userinfo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='status',
            field=models.BooleanField(default=True, verbose_name='是否正常'),
        ),
    ]
